### ISSUE TITLE
Dependency on atmel-rf-driver

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/nanostack-hal-mbed-cmsis-rtos#7]
This module's implementation of arm_hal_random depends on atmel-rf-driver providing rf_read_random and rf_read_mac_address.

Since it is nowhere documented in the porting guide that a driver needs to be called 'driverRFPhy', nor that it has to provide the functions mentioned above, it gets pretty confusing when trying to get a different radio up and running with Nanostack.

**Comment by hasnainvirk** [comment]
Was merged in https://github.com/ARMmbed/nanostack-hal-mbed-cmsis-rtos/pull/8
Hence closing.
